### PR TITLE
Enable apt pinning

### PR DESCRIPTION
**Pull request by lhoss**
### Short description:
Added optional apt pinning by setting the pin priority in `mesos_apt_pin_priority`(disabled by default)
Thx @scaronni for implementing 👍 

Same feature will follow for the marathon role

### CODE REVIEW

**Comment by ernestas-poskus** [comment]
Failing on

```
TASK [role_under_test : Add mesosphere repo] ***********************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to validate the SSL certificate for repo.mesosphere.com:443. Make sure your managed systems have a valid CA certificate installed. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible"}

**Comment by scaronni** [comment]
That's because there is no longer a repo.mesosphere.com domain :/

**Comment by scaronni** [comment]
PR rebased with the correct url in `defaults/main.yml`.

**Comment by ernestas-poskus** [comment]
Failing

```
TASK [role_under_test : Downloading and enable the EPEL repository definitions.] ***
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failure downloading https://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-10.noarch.rpm, 'NoneType' object has no attribute 'read'"}
 [WARNING]: Could not create retry file
```

**Comment by lhoss** [comment]
> `Failure downloading https://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-10.noarch.rpm`

Something is wrong with the EPEL url, which does not exist (anymore?), I manually checked with `curl`.

I googled and found the correct URL: http://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-10.noarch.rpm  ( means `download.` instead of `dl.` )
Ref: https://fedoraproject.org/wiki/EPEL/FAQ#Using_EPEL

**Comment by scaronni** [comment]
EPEL repositories' configuration package has been changed long ago for these kind of situations. There is an unversioned copy just for this reason:

https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm
https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

I updated the PR.

**Pull request merged**
