### PR TITLE
Disable unused Mesos services

### LINKED ISSUE #44: Systemd services remain enabled despite install mode
When running the `master` install mode, the `mesos-slave` services remain enabled in systemd (more specifically, the file at `/etc/systemd/system/multi-user.target.wants/mesos-slave.service` still exists), and vice versa. On a reboot, the system will continuously try to restart these services which should not be running.

The following task (and a similar one for disabling mesos-master) should fix this issue. I'll open a PR after some additional testing.

``` yaml
service: name=mesos-slave enabled=no
when: mesos_install_mode == "master"
```

### PR DESCRIPTION
**Pull request by DavidWittman**
Closes #44

### CODE REVIEW

**Comment by ninthnails** [comment]
Very neat stuff! I came across this issue many times wondering why the hell slave service was started even though i was not suppose to install it. Now it all make sense!

One thing I would like to see though is simple test in the build playbook. That won't be trivial to do but it will increase robustness of the role. Unfortunately the tests only install in master-slave. Some refactor needed.

**Comment by DavidWittman** [comment]
:+1: for better testing around these types of things. Have you guys used [Molecule](https://github.com/metacloud/molecule) at all? I've been using Test Kitchen for testing most of my roles but this looks much better suited for Ansible.

**Comment by JasonGiedymin** [comment]
Almost all our roles "`try`" to use vagrant. The `ci/` playbook simply uses this role. See [here](https://github.com/AnsibleShipyard/ansible-mesos/tree/master/tests) and [here](https://github.com/AnsibleShipyard/ansible-zookeeper/tree/master/ci).

This is somewhat similar to how molecule works. In fact many of the things it does we do here albeit more verbosely.

See this repo's [Vagrantfile](https://github.com/AnsibleShipyard/ansible-mesos/blob/master/Vagrantfile) and [Zookeeper Vagrantfile](https://github.com/AnsibleShipyard/ansible-zookeeper/blob/master/Vagrantfile).

The things I like about this are:
  -[x] uses vagrant, easy to get on any platform (along with vbox or parallels if that suites your fancy)
  -[x] uses tests written with ansible 
  -[x] no need for additional dependencies
  -[x] weirdly enough you can have the same tests triggered with travis, see [here](https://travis-ci.org/AnsibleShipyard/ansible-zookeeper)

**Comment by JasonGiedymin** [comment]
That being said, if it helps with easing testing than what we've already got here I'm all for it.

**Comment by ernestas-poskus** [comment]
@DavidWittman bump version https://github.com/AnsibleShipyard/ansible-mesos/blob/master/vars/main.yml#L2 and this will get merged

**Comment by DavidWittman** [comment]
@ernestas-poskus rebased and bumped version

**Comment by ernestas-poskus** [comment]
@DavidWittman  please squash commits

**Comment by DavidWittman** [comment]
You can squash them on merge now in Github if you so please.

**Comment by ernestas-poskus** [comment]
@DavidWittman 

I have no permissions to enable Github squash, please do it on your side.

**Comment by DavidWittman** [comment]
@ernestas-poskus You don't have this option?

image

**Comment by ernestas-poskus** [comment]
@DavidWittman 

Unfortunately no

screenshot from 2016-06-09 19-35-05

so as Settings for repo are absent 
screenshot from 2016-06-09 19-34-57

**Comment by DavidWittman** [comment]
@ernestas-poskus You have to click "Merge pull request" first and then you'll get a dropdown on the "Confirm merge" button. It's confusing.

**Comment by ernestas-poskus** [comment]
You got me :smile: this is the first time I am doing this without CLI

**Comment by ernestas-poskus** [comment]
Thank you for contribution :bow:

**Pull request merged**
