### PR TITLE
Changed Mesos version to 0.25.0 package 0.2.70 in order to work with …

### PR DESCRIPTION
**Pull request by veacks**
…the latest version of Docker (1.9.1)

Fixing the opened issue [#37](https://github.com/AnsibleShipyard/ansible-mesos/issues/37)

### CODE REVIEW

**Comment by JasonGiedymin** [comment]
Right now ansible-docker looks out of date somewhat. We are working to get it updated.

**Comment by veacks** [comment]
Ansible-Docker on Ubuntu worked just fine for me.

Took me awhile to figure out that last version of Docker was incompatible with Mesos 0.21 and then needed to update to 0.25.

cf: In the [0.25 release notes](https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12311242&version=12329852).

[MESOS-2986](https://issues.apache.org/jira/browse/MESOS-2986) - Docker version output is not compatible with Mesos

**Comment by JasonGiedymin** [comment]
I only say because docker-engine is now recommended for all distros over say lxc-docker.
i.e. for ubuntu ()
```shell
# Purge the old repo if it exists.
$ apt-get purge lxc-docker
```shell

**Comment by JasonGiedymin** [comment]
Fyi, v0.26 is right around the corner, we better get moving :-P

**Pull request merged**
