### PR TITLE
Fix containerization + Make APT-Package name more generic with varialbes

### PR DESCRIPTION
**Pull request by guenhter**
### Short description:

I found the following issue(s) or bug(s):
  - "docker" was missing for containerization (https://mesosphere.github.io/marathon/docs/native-docker.html)

_And/OR_

I found that the following _enhancement_ is worthwhile:
  - Extract the whole "mesos=..." package name as variable

### CODE REVIEW

**Comment by ernestas-poskus** [comment]
:+1:

**Comment by ernestas-poskus** [comment]
@guenhter rebase please and I will get this merged

**Comment by guenhter** [comment]
Done.

**Comment by ernestas-poskus** [comment]
thank you for contribution :+1:

**Pull request merged**
