### PR TITLE
Version bump to 0.21.0

### PR DESCRIPTION
**Pull request by mhamrah**

### CODE REVIEW

**Comment by JasonGiedymin** [comment]
I see the test failing, trying to pull and try on my local.

**Comment by JasonGiedymin** [comment]
PRs #18 and #19 will fix Travis.

You want to merge those in first, and then update this PR so that Travis will light up green?

**Comment by mhamrah** [comment]
Yeah, no problem.

**Comment by mhamrah** [comment]
I can do it tomorrow

**Comment by JasonGiedymin** [comment]
A heads up, I have enabled third security for this org. It may force you to validate member's keys. Just in case follow the link from the error message github responds with. Once done retry the push and you should be good to go.

**Comment by JasonGiedymin** [comment]
I'm going to start merging, and then that leaves this PR. I can update it tonight if you don't.

**Comment by JasonGiedymin** [comment]
Technically we can merge this now. :-)

**Comment by mhamrah** [comment]
Nice! Sorry, got held up yesterday. I'll take care of my updates today.

**Comment by JasonGiedymin** [comment]
Everything passed, It's all good!

**Pull request merged**
